# Generated by Django 6.0.5 on 2026-05-31 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora_agendada', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'PENDENTE'), (2, 'CONCLUÍDA'), (3, 'CANCELADA')], default=1)),
                ('prioridade', models.IntegerField(choices=[(1, 'BAIXA'), (2, 'MÉDIA'), (3, 'ALTA')], default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
